version: '3.1'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  iisDb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mameradiiis
      - POSTGRES_USER=root
      - POSTGRES_DB=iisDb
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432